### ISSUE TITLE
AttributeError: 'LSTMNetwork' object has no attribute 'step_prev_hidden_layer'

### ISSUE THREAD

**Issue by brett-daley** [rll/rllab#188]
I am trying to run a simple Tensorflow example on CartPole with the LSTMNetwork. It appears a critical member is missing from the class. I also get the same error when using the GRUNetwork.

> Error while instantiating <class 'sandbox.rocky.tf.policies.categorical_lstm_policy.CategoricalLSTMPolicy'>
> Traceback (most recent call last):
>   File "rllab/rllab/misc/instrument.py", line 1360, in concretize
>     *args, **kwargs)
>   File "rllab/sandbox/rocky/tf/policies/categorical_lstm_policy.py", line 100, in \_\_init\_\_
>     prob_network.step_prev_hidden_layer.input_var,
> AttributeError: 'LSTMNetwork' object has no attribute 'step_prev_hidden_layer'

- gym (0.8.2)
- tensorflow (1.1.1)
- rllab (82a1499)

Here is my sample code:
```
from rllab.baselines.zero_baseline import ZeroBaseline
from rllab.envs.normalized_env import normalize
from rllab.misc.instrument import stub, run_experiment_lite
from rllab.envs.gym_env import GymEnv

from sandbox.rocky.tf.envs.base import TfEnv
from sandbox.rocky.tf.algos.trpo import TRPO
from sandbox.rocky.tf.policies.categorical_lstm_policy import CategoricalLSTMPolicy

stub(globals())

env = TfEnv(normalize(GymEnv('CartPole-v0', force_reset=True, record_video=False)))

policy = CategoricalLSTMPolicy(
    name='policy',
    env_spec=env.spec,
    hidden_dim=128,
    )

baseline = ZeroBaseline(env_spec=env.spec)

algo = TRPO(
    env=env,
    policy=policy,
    baseline=baseline,
    batch_size=1000,
    n_itr=50,
    discount=0.99,
    step_size=0.01,
)

run_experiment_lite(
    algo.train(),
    n_parallel=1,
    snapshot_mode="last",
    seed=1
)
```

**Comment by chelseas** [comment]
It looks like issue #141 may solve your problem. I was having the same one.

**Comment by brett-daley** [comment]
Thanks for your reply. That got the GaussianLSTMPolicy working for me, but for some reason the CategoricalLSTMPolicy still isn't working. I think there might be something else wrong too.

I noticed that [these lines](https://github.com/rll/rllab/blob/b3a28992eca103cab3cb58363dd7a4bb07f250a0/sandbox/rocky/tf/policies/categorical_lstm_policy.py#L100-L101) (which throw the error) in the CategoricalLSTMPolicy are different from the [analogous line](https://github.com/rll/rllab/blob/b3a28992eca103cab3cb58363dd7a4bb07f250a0/sandbox/rocky/tf/policies/gaussian_lstm_policy.py#L112) in the GaussianLSTMPolicy. In the LSTMNetwork class, [step_prev_state_layer](https://github.com/rll/rllab/blob/b3a28992eca103cab3cb58363dd7a4bb07f250a0/sandbox/rocky/tf/core/network.py#L382) exists, but `step_prev_hidden_layer` and `step_prev_cell_layer` do not. To me, it seems like the code was refactored at some point, but the CategoricalLSTMPolicy was forgotten.

I think the CategoricalGRUPolicy has a [similar issue](https://github.com/rll/rllab/blob/b3a28992eca103cab3cb58363dd7a4bb07f250a0/sandbox/rocky/tf/policies/categorical_gru_policy.py#L94).

I'll see if I can edit these files to get my original example to run. If this a bug, it would be nice to fix it. Otherwise, I can probably close the issue, since I don't really need the categorical networks.

**Comment by brett-daley** [comment]
After re-reading issue #141 I realized that these problems were previously identified and that's probably what you were referring to (I thought you were talking about the finite differences, which I also wasn't doing). I still think a pull request should be opened so others don't run into this again, because it seems to be relatively common.

**Comment by chelseas** [comment]
I would encourage you to submit a pull request, but unfortunately, rllab does not seem to be maintained these days. I hear that garage is a fork of rllab that is under regular development.
