### ISSUE TITLE
example trpo_cartpole_recurrent.py does not work

### ISSUE THREAD

**Issue by lchenat** [rll/rllab#189]
when I ran examples/trpo_cartpole_recurrent.py I encountered the following errors:

Traceback (most recent call last):
  File "/home/***/Documents/rllab-master/scripts/run_experiment_lite.py", line 137, in <module>
    run_experiment(sys.argv)
  File "/home/***/Documents/rllab-master/scripts/run_experiment_lite.py", line 121, in run_experiment
    method_call(variant_data)
  File "trpo_cartpole_recurrent.py", line 14, in run_task
    env_spec=env.spec,
  File "/home/***/Documents/rllab-master/rllab/policies/gaussian_gru_policy.py", line 50, in __init__
    output_nonlinearity=output_nonlinearity,
  File "/home/***/Documents/rllab-master/rllab/core/network.py", line 228, in __init__
    b=l_output_flat.b,
  File "/home/***/anaconda2/envs/py36/lib/python3.6/site-packages/lasagne/layers/dense.py", line 78, in __init__
    super(DenseLayer, self).__init__(incoming, **kwargs)
  File "/home/***/anaconda2/envs/py36/lib/python3.6/site-packages/lasagne/layers/base.py", line 44, in __init__
    if any(d is not None and d <= 0 for d in self.input_shape):
  File "/home/***/anaconda2/envs/py36/lib/python3.6/site-packages/lasagne/layers/base.py", line 44, in <genexpr>
    if any(d is not None and d <= 0 for d in self.input_shape):
TypeError: '<=' not supported between instances of 'tuple' and 'int'

**Comment by ryanjulian** [comment]
Did you install the conda env directly from the environment.yml? It seems that your env uses python 3.6 (environment.yml specifies Python 3.5).
